### ISSUE TITLE
View and download submission data

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/tape-data-system#4]
Teams should be able to view ODK submissions for any of their xlsforms. The submission viewing page should be available from:

- the ODK Form Management page (perhaps as a link within the table, so you can view submissions from a specific form)
- the sidebar (inside a new nav group called "data")
- as an Action on the TeamDashbaord that becomes visible once the team has completed the Step 0 and preparation phase. 

## Page functionality
- The page should show a brief summary of the data collected so far: total count of submissions; space for other summaries (*TODO - link to other issues*)
- The page should show a table of the submissions that have been brought into the platform.
- Users should be able to download the data.

**Comment by dave-mills** [comment]
For reference, the 'survey monitoring' page in the TAPE GIZ Platform looked like this: 

![CleanShot 2024-05-08 at 10 54 48](https://github.com/stats4sd/tape-data-system/assets/5711101/e2e6502f-22bc-48bb-a2ea-a0e166584333)

Code Reference: 

https://github.com/stats4sd/tape-giz/blob/10dbb0961f139ce6902f19399386f438f5af14c6/app/Http/Controllers/SurveyMonitoringController.php

**Comment by dan-tang-ssd** [comment]
Thank you Dave.

I pulled latest code for tape giz project, I played around but I cannot find out how to go to the "Survey Monitoring" page.
Would you tell me where is it?

![image](https://github.com/stats4sd/tape-data-system/assets/86968034/0354e787-6c5a-4e6d-ba1b-5021008604e9)

**Comment by dave-mills** [comment]
The old backpack interface is hidden from users, but not disabled. Go to {appurl}/admin, or directly to that page: {app_url}/admin/team/{team_id}/live-form

**Comment by dave-mills** [comment]
@dan-tang-ssd - Just FYI, in case you hadn't seen this yet - one of the updates I made over the weekend was to bring the monitoring page you created into the main XlsformResource -> ViewXlsform page so we can see this monitoring info *and* the submission list on the same page, which addresses one of the points in this issue.

**Comment by dan-tang-ssd** [comment]
The latest code can now view and download submission data:
1. Extract from ODK central API directly
2. Extract from local database generic tables entities and entity_values

I would consider this issue is resolved.
I will close this issue now.
