### ISSUE TITLE
Ensure that all the required data models exist for the survey

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/tape-data-system#55]
We need:
- a 'main survey' dataset and linked data model.
- a locationrpt dataset (no model needed, as we don't need to keep that data)
- a fieldsurvey photo  dataset and linked data model. 

All data models used (those, plus all the performance_* tables) need a submission_id to link to the submission.

**Comment by dave-mills** [comment]
@dan-tang-ssd  - this continues the discussion from #20. I still think we need to change `odk_id` in the custom data models.

For now, we are assuming that a submission only ever creates new data model entries - it does not change or update existing entries. So a custom data model (e.g. `DrinkSurveyMain`) is linked to a single submission. The default approach in Laravel for this situation is to add a `submission()` relationship method to `DrinkSurveyMain`, linked via submission_id. I don't see any reason not to do this. 

The challenge is with the reverse. In the package, we do not know about `DrinkSurveyMain`, so we can't add a relationship `drinkSurveyMain()` to `Submission`. But I don't see this as a reason not to do the part above. 

Eventually, we'll want to handle cases where a submission doesn't create new entries, but instead updates existing entries. (Consider an example where we have a list of farms, and then a submission includes an existing farm_id and some new information to add to the farms table). I think that will require a many-many polymorphic relationship between Submission and various data models, which I think *is* possible to setup in advance. (Similar to how we have `owners` of Xlsform models...)

For now, I am going to update from `odk_id` to `submission_id` so that we are following the conventional practice for linking 2 data models together via a 1-many relationship.

**Comment by dan-tang-ssd** [comment]
Hi Dave,

Yes, it is better to use submission_id instead of odk_id.

I did not change it yet because I was engaged to "Edit Submission" feature before. Just want to complete that feature before changing other stuff...

**Comment by dave-mills** [comment]
Great. In that case I'll add the submission_id to the various data models and leave you to update the back-end logic references to this variable.
