### ISSUE TITLE
The Performance_Activities and Performance_Machines worksheets are empty in the main data export

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/tape-data-system#77]
I'm pretty sure they are not meant to be!

**Comment by dan-tang-ssd** [comment]
I did below preliminary checkings:
 - check live database tables performance_activities, performance_machines, no record found
 - find some related ODK variable names in ODK form: acname, mname
 - check table entity_values, no records found for acname and mname
 - check ODK submission JSON content, acname and mname are existed  
 - check related dataset definition, they look similar to other datasets

Possible cause:
 - are ODK variables located in correct repeat group?

Data extraction excel file:
[Tape GIZ-data-export-2024-07-12 14_17_00.xlsx](https://github.com/user-attachments/files/16232857/Tape.GIZ-data-export-2024-07-12.14_17_00.xlsx)
